services: 
  mysql:
    image: mysql
    container_name: mysql_container2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_todo-list:/var/lib/mysql

  todo-list-api:
    image: pipeanayaparada/todo-list:latest
    depends_on:
      - mysql
    container_name: TodoListApp
    ports:
      - "3005:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  mysql_todo-list:
